services:
  postgres:
    container_name: database
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  postgres-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
